networks:
  global_network:
    external: true

services:
  redis:
    image: redis:8.0-M02-alpine3.20
    container_name: redis
    restart: unless-stopped
    command: ['redis-server', '--notify-keyspace-events', 'Ex']
    ports:
      - 6379:6379
    networks:
      - global_network