networks:
  global_network:
    external: true

services:
  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    restart: unless-stopped
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - global_network