services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: gateway
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - ./proto:/proto
    networks:
      - global_network

networks:
  global_network:
    external: true
