networks:
  global_network:
    external: true

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    networks:
      - global_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data