export enum InventoryType {
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  IN_STOCK = 'IN_STOCK',
  RUNNING_LOW = 'RUNNING_LOW',
  SOLD_OUT = 'SOLD_OUT',
  AVAILABLE = 'AVAILABLE',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
}
